task:
  name: Tests (linux)
  container:
    image: ubuntu:latest
  install_script:
    - apt-get update
    - apt-get -y install python3 python3-venv python3-dev g++
  test_script: 
    - bash ./pytest.sh


task:
  name: Tests (macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  script:
    - brew install libomp
    - brew install python@3.12
    - $(brew --prefix python@3.12)/bin/python3.12 -m venv .test_venv
    - source .test_venv/bin/activate
    - pip install --upgrade pip
    - sh ./pytest.sh


