r"""
==================================
Kernel smmoting - Nadaraya-Watson estimator - NumPy API
==================================

Consider a dataset :math:`(x_i, y_i)` generated by the following process:

.. math::
        y_i = f(x_i) + \text{noise}.

We can build a non-parametric estimator by computing weighted averages of the dependent variable, 
where the weights are computed using a kernel of our choosing :  

.. math::
       \hat y(x) = \frac{\Sum y_i K(x, x_i)}{\Sum K(x, x_i)},

where :math:`K` is a symmetric, positive definite linear operator
defined through the :ref:`KeOps generic syntax <part.generic_formulas>`.

This is called the Nadaraya-Watson estimator. 
 
"""


########################################################################
# Setup
# ----------------------
#
# Standard imports:

import numpy as np
from pykeops.numpy import LazyTensor
import matplotlib.pyplot as plt
from matplotlib import cm

######################################################################
# Smoothing in 1D
# -------------------


def kernel_smoother(x, y, bandwidth=0.1, grid_size=100, kernel='gaussian'):
    """
    Kernel smoother with single input and single output using KeOps.

    Parameters:
    - x: Independent variable (numpy array)
    - y: Dependent variable (numpy array)
    - bandwidth: Kernel bandwidth parameter
    - grid_size: Number of points for the evaluation grid
    - kernel: 'gaussian', 'quadratic' or custom kernel function

    Returns:
    - grid_x: Grid coordinates
    - smoothed_grid_y: Smoothed output variable on grid
    """

    # Create grid points
    x_min, x_max = x.min(), x.max()
    grid_x = np.linspace(x_min, x_max, grid_size)

    # Create LazyTensors
    x_j = LazyTensor(x[None, :, None])  # Shape: [1, n_samples, 1]
    grid_i = LazyTensor(grid_x[:, None, None])  # Shape: [grid_size, 1, 1]

    # Compute Gaussian kernel weights for grid points
    if kernel == 'gaussian':
        D_grid_sample = ((grid_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (-D_grid_sample / (2 * bandwidth**2)).exp()  # Shape: [grid_size, n_samples]
    # Compute quadratic kernel weights for grid points
    elif kernel == 'quadratic':
        D_grid_sample = ((grid_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (D_grid_sample < bandwidth**2)*(1-D_grid_sample.sqrt()/bandwidth)**2
    else:
        K_grid_sample = kernel(grid_i, x_j, bandwidth=bandwidth)

    # Normalize kernel weights (row-wise sum to 1)
    K_grid_sample_sum = K_grid_sample.sum(dim=1)[:, None]
    K_grid_sample = K_grid_sample / K_grid_sample_sum

    # Perform kernel smoothing for output variable on grid
    smoothed_grid_y = K_grid_sample@y

    return grid_x, smoothed_grid_y

#######################################################################
# Display the model's predictions:
#

def plot_smoothing_results(x, y, grid_x, smoothed_grid_y):
    """
    Plot the original and smoothed data in 2D.

    Parameters:
    - x: Original input variable
    - y: Original output variable
    - grid_x: Grid coordinates
    - smoothed_grid_y: Smoothed output variable on grid
    """
    plt.figure(figsize=(12, 6))

    # Plot original data points
    plt.scatter(x, y, c='red', s=30, alpha=0.7, label='Original Data')

    # Plot smoothed values on grid
    plt.plot(grid_x, smoothed_grid_y, 'b-', linewidth=2, label='Smoothed Function')

    plt.title('Kernel Smoothing Results')
    plt.xlabel('Input (x)')
    plt.ylabel('Output (y)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

#######################################################################
# Example usage

# Generate some data:

np.random.seed(0)
n_samples = 5000

# Independent variable
x = np.linspace(-5, 5, n_samples)

# Dependent variable
true_y = np.random.randn(1)*np.sin(x) + np.random.randn(1)*np.cos(x) + np.random.randn(1) * x
y = true_y + 0.2 * np.random.randn(n_samples)

# Apply kernel smoother
grid_x, smoothed_grid_y = kernel_smoother(x, y, bandwidth=0.3, grid_size=200, kernel='quadratic')

# Plot the results
plot_smoothing_results(x, y, grid_x, smoothed_grid_y)

######################################################################
# Smoothing in 1D with pointwise variance estimation
# -------------------
# Performing a second smoothing in sequence, we can estimate the pointwise variance of the estimator :math:`\hat V_y(x))`
# where the weights are computed using a kernel of our choosing :  
#
# .. math::
#        \hat V_y(x) = \frac{\Sum (y_i-\hat y(x)) K(x, x_i)}{\Sum K(x, x_i)},
#
# This is especially useful when the noise term depends on :math:`y`.

def kernel_smoother(x, y, bandwidth=0.1, grid_size=100, kernel='gaussian'):
    """
    Kernel smoother with single input and single output using KeOps.

    Parameters:
    - x: Independent variable (numpy array)
    - y: Dependent variable (numpy array)
    - bandwidth: Kernel bandwidth parameter
    - grid_size: Number of points for the evaluation grid
    - kernel: 'gaussian', 'quadratic' or custom kernel function

    Returns:
    - grid_x: Grid coordinates
    - smoothed_grid_y: Smoothed output variable on grid
    """

    # Create grid points
    x_min, x_max = x.min(), x.max()
    grid_x = np.linspace(x_min, x_max, grid_size)

    # Create LazyTensors
    x_j = LazyTensor(x[None, :, None])  # Shape: [1, n_samples, 1]
    x_i = LazyTensor(x[:, None, None])  # Shape: [n_samples, 1, 1]
    grid_i = LazyTensor(grid_x[:, None, None])  # Shape: [grid_size, 1, 1]

    # Compute Gaussian kernel weights for grid points
    if kernel == 'gaussian':
        D_ij = ((x_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_ij = (-D_ij / (2 * bandwidth**2)).exp()  # Shape: [grid_size, n_samples]
    # Compute quadratic kernel weights for grid points
    elif kernel == 'quadratic':
        D_ij = ((x_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_ij = (D_ij < bandwidth**2)*(1-D_ij.sqrt()/bandwidth)**2
    else:
        K_ij = kernel(x_i, x_j, bandwidth=bandwidth)

    # Normalize kernel weights (row-wise sum to 1)
    K_ij_sum = K_ij.sum(dim=1)[:, None]
    K_ij = K_ij / K_ij_sum

    # Perform kernel smoothing for output variable on grid
    smoothed_y = K_ij@y
    mse = (y-smoothed_y)**2

    # Compute Gaussian kernel weights for grid points
    if kernel == 'gaussian':
        D_grid_sample = ((grid_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (-D_grid_sample / (2 * bandwidth**2)).exp()  # Shape: [grid_size, n_samples]
    # Compute quadratic kernel weights for grid points
    elif kernel == 'quadratic':
        D_grid_sample = ((grid_i - x_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (D_grid_sample < bandwidth**2)*(1-D_grid_sample.sqrt()/bandwidth)**2
    else:
        K_grid_sample = kernel(grid_i, x_j, bandwidth=bandwidth)

    # Normalize kernel weights (row-wise sum to 1)
    K_grid_sample_sum = K_grid_sample.sum(dim=1)[:, None]
    K_grid_sample = K_grid_sample / K_grid_sample_sum

    # Perform kernel smoothing for output variable on grid
    smoothed_grid_y = K_grid_sample@y
    grid_mse = K_grid_sample@mse

    return grid_x, smoothed_grid_y, grid_mse

#######################################################################
# Display the model's predictions:
#

def plot_smoothing_results(x, y, grid_x, smoothed_grid_y, grid_mse):
    """
    Plot the original and smoothed data in 2D.

    Parameters:
    - x: Original input variable
    - y: Original output variable
    - grid_x: Grid coordinates
    - smoothed_grid_y: Smoothed output variable on grid
    """
    plt.figure(figsize=(12, 6))

    # Plot original data points
    plt.scatter(x, y, c='red', s=30, alpha=0.7, label='Original Data')

    # Plot smoothed values on grid
    plt.plot(grid_x, smoothed_grid_y, 'b-', linewidth=2, label='Smoothed Function')
    plt.plot(grid_x, smoothed_grid_y+2*np.sqrt(grid_mse), 'b--', linewidth=2, label='Smoothed Function')
    plt.plot(grid_x, smoothed_grid_y-2*np.sqrt(grid_mse), 'b--', linewidth=2, label='Smoothed Function')

    plt.title('Kernel Smoothing Results')
    plt.xlabel('Input (x)')
    plt.ylabel('Output (y)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

#######################################################################
# Example usage

# Generate some data:

np.random.seed(0)
n_samples = 5000

# Independent variable
x = np.linspace(-5, 5, n_samples)

# Dependent variable
true_y = np.random.randn(1)*np.sin(x) + np.random.randn(1)*np.cos(x) + np.random.randn(1) * x
y = true_y + 0.2 * np.random.randn(n_samples)*(2+np.cos(5*x))*np.sqrt(np.abs(y))

# Apply kernel smoother
grid_x, smoothed_grid_y, grid_mse = kernel_smoother(x, y, bandwidth=0.3, grid_size=200, kernel='quadratic')

# Plot the results
plot_smoothing_results(x, y, grid_x, smoothed_grid_y, grid_mse)


#########################################################################
# Interpolation in 2D
# -------------------


def kernel_smoother(x, y, bandwidth=1.0, grid_size=100, kernel='gaussian'):
    """
    Kernel smoother with single input and single output using KeOps.

    Parameters:
    - x: Input variable (numpy array or torch tensor)
    - y: Output variable (numpy array or torch tensor)
    - bandwidth: Kernel bandwidth parameter
    - grid_size: Number of points for the grid
    - kernel: 'gaussian', 'quadratic' or custom kernel function

    Returns:
    - xx: First grid coordinate
    - yy: Second grid coordinate
    - bb: Smoothed output variable on grid
    """


    # Create grid points
    x_min, x_max = x[:,0].min(), x[:,0].max()
    y_min, y_max = x[:,1].min(), x[:,1].max()
    grid_x = np.linspace(x_min, x_max, grid_size)
    grid_y = np.linspace(y_min, y_max, grid_size)
    xx, yy = np.meshgrid(grid_x, grid_y)

    G = np.hstack([xx.reshape(-1,1), yy.reshape(-1,1)])

    # Create LazyTensors for efficient computation
    X_i = LazyTensor(x[:, None, :])  # Shape: [n_samples, 1, 2]
    print(X_i.shape)
    X_j = LazyTensor(x[None, :, :])  # Shape: [1, n_samples, 2]
    G_i = LazyTensor(G[:, None, :])  # Shape: [grid_size*grid_size, 1, 2]

    # Compute pairwise squared distances between samples
    D_ij = ((X_i - X_j)**2).sum(dim=2)  # Shape: [n_samples, n_samples]

    # Compute Gaussian kernel weights for grid points
    if kernel == 'gaussian':
        D_grid_sample = ((G_i - X_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (-D_grid_sample / (2 * bandwidth**2)).exp()  # Shape: [grid_size, n_samples]
    # Compute quadratic kernel weights for grid points
    elif kernel == 'quadratic':
        D_grid_sample = ((G_i - X_j)**2).sum(dim=2)  # Shape: [grid_size, n_samples]
        K_grid_sample = (D_grid_sample < bandwidth**2)*(1-D_grid_sample.sqrt()/bandwidth)**2
    else:
        K_grid_sample = kernel(G_i, X_j, bandwidth=bandwidth)

    # Normalize kernel weights (row-wise sum to 1)
    K_grid_sample_sum = K_grid_sample.sum(dim=1)[:, None]  # Using [:, None] instead of keepdim
    K_grid_sample = K_grid_sample / K_grid_sample_sum

    # Perform kernel smoothing for output variable on grid
    bb = K_grid_sample@y


    return xx, yy, bb.reshape(xx.shape)

def plot_smoothing_results(x, b, xx, yy, bb):
    """
    Plot the original and smoothed data in 2D.

    Parameters:
    - x: Original input variable
    - b: Original output variable
    - xx: First grid coordinate
    - yy: Second grid coordinate
    - bb: Smoothed output variable on grid
    """
    plt.figure(figsize=(12, 6))
    plt.pcolormesh(xx, yy, bb, cmap="coolwarm")
    plt.scatter(x[:,0], x[:,1], c=b, s=25000 / len(x), cmap="bwr")
    plt.title('Kernel Smoothing Results')
    plt.tight_layout()
    plt.show()

#######################################################################
# Example usage

# Generate some data:

# Sampling locations:
N = 10000
x = np.random.rand(N, 2)

# Some random-ish 2D signal:
b = np.sum((x - 0.5) ** 2, axis=1)[:, None]
b[b > 0.4**2] = 0
b[b < 0.3**2] = 0
b[b >= 0.3**2] = 1
b = b + 0.05 * np.random.randn(N, 1)

# Add 25% of outliers:
Nout = N // 4
b[-Nout:] = np.random.rand(Nout, 1)

# Apply kernel smoother
xx, yy, bb = kernel_smoother(x, b, bandwidth=0.05, grid_size=200)

# Plot the results
plot_smoothing_results(x, b, xx, yy, bb)
