import ctypes
import os
import sysconfig

import keopscore.config
from keopscore.binders.LinkCompile import LinkCompile
from keopscore.utils.gpu_utils import custom_cuda_include_fp16_path
from keopscore.utils.messages import KeOps_Error, KeOps_Message
from keopscore.utils.system_utils import KeOps_OS_Run

jit_source_file = os.path.join(
    keopscore.config.path.get_base_dir_path(), "binders", "nvrtc", "keops_nvrtc.cpp"
)

jit_compile_src = os.path.join(
    keopscore.config.path.get_base_dir_path(), "binders", "nvrtc", "nvrtc_jit.cpp"
)


def jit_compile_dll():
    return os.path.join(
        keopscore.config.path.get_build_folder(),
        "nvrtc_jit" + sysconfig.get_config_var("SHLIB_SUFFIX"),
    )


class Gpu_link_compile(LinkCompile):
    source_code_extension = "cu"

    def __init__(self):
        # checking that the system has a Gpu :
        if not (
            keopscore.config.cuda.get_use_cuda()
            and keopscore.config.cuda.get_n_visible_devices()
        ):
            KeOps_Error(
                "Trying to compile cuda code... but we detected that the system has no properly configured cuda lib."
            )

        LinkCompile.__init__(self)
        # these are used for JIT compiling mode
        # low_level_code_file is filename of low level code (PTX for Cuda) or binary (CUBIN for Cuda)
        # generated by the JIT compiler, e.g. 7b9a611f7e_nvrtc.{ptx,cubin}
        self.low_level_code_file = os.path.join(
            keopscore.config.path.get_build_folder(),
            self.gencode_filename + "_nvrtc." + keopscore.config.cuda.get_ir_type(),
        ).encode("utf-8")

        self.my_c_dll = ctypes.CDLL(jit_compile_dll(), mode=os.RTLD_LAZY)

        # file to check for existence to detect compilation is needed
        self.file_to_check = self.low_level_code_file

    def generate_code(self):
        # method to generate the code and compile it
        # generate the code and save it in self.code, by calling get_code method from GpuReduc class :
        self.get_code()
        # write the code in the source .cu file
        self.write_code()
        # we execute the main dll, passing the code as argument, and the name of the low level code file to save the assembly instructions

        res = self.my_c_dll.Compile(
            ctypes.create_string_buffer(self.low_level_code_file),
            ctypes.create_string_buffer(self.code.encode("utf-8")),
            ctypes.c_int(self.use_half),
            ctypes.c_int(self.use_fast_math),
            ctypes.c_int(self.device_id),
            ctypes.create_string_buffer(
                (custom_cuda_include_fp16_path() + os.path.sep).encode("utf-8")
            ),
        )
        if res != keopscore.config.cuda.CUDA_SUCCESS:
            KeOps_Error(
                f"Error when compiling {self.low_level_code_file} formula (error in nvrtcCompileProgram, nvrtcResult={res})"
            )
        # retreive some parameters that will be saved into info_file.
        self.tagI = self.red_formula.tagI
        self.dim = self.red_formula.dim

    @staticmethod
    def get_compile_command(
        sourcename=jit_source_file,
        dllname=keopscore.config.path.get_jit_binary(),
        extra_flags="",
    ):
        # This is about the main KeOps binary (dll) that will be used to JIT compile all formulas.
        # If the dll is not present, it compiles it from source, except if check_compile is False.

        return (
            f"{keopscore.config.cxx.get_cxx_compiler()} "
            f"{keopscore.config.cuda.get_preprocessing_options()} "
            f"{keopscore.config.cxx.get_compile_options()} "
            f"{keopscore.config.path.get_include_options()} "
            f"{keopscore.config.cuda.get_include_options()} "
            f" {extra_flags} "
            f"{sourcename} "
            f"{keopscore.config.cxx.get_linking_options()} "
            f"{keopscore.config.cuda.get_linking_options()} "
            f"-o {dllname}"
        )

    @staticmethod
    def compile_jit_compile_dll():
        KeOps_Message("Compiling cuda jit compiler engine", flush=True, end="", level=1)
        KeOps_Message(
            " in cache folder " + keopscore.config.path.get_build_folder(),
            flush=True,
            end="",
            level=2,
        )
        KeOps_Message(" ... ", flush=True, end="", use_tag=False, level=1)
        command = Gpu_link_compile.get_compile_command(
            sourcename=jit_compile_src, dllname=jit_compile_dll()
        )
        out = KeOps_OS_Run(command)
        if out.returncode != 0:
            KeOps_Error(
                f"Error compiling cuda/nvrtc binder {jit_compile_dll()}. See compiler output above."
            )
        else:
            KeOps_Message("OK", use_tag=False, flush=True, level=1)
