name: Linux CPU Test

on:
  push:
  pull_request:

jobs:
  tests-linux:
    name: Tests (Linux CPU)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run tests
        run: bash ./pytest.sh