name: macOS Test

on:
  push:
  pull_request:

jobs:
  tests-macos:
    name: Tests (macOS CPU)
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: brew install libomp

      - name: Run tests
        run: bash ./pytest.sh
