name: macOS Test

on:
  push:
  pull_request:

jobs:
  tests-macos:
    name: Tests (macOS ${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - arch: ARM
            os: macos-latest
          - arch: Intel
            os: macos-26-intel
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: brew install libomp

      - name: Run tests
        run: bash ./pytest.sh
