# Launch test on various platforms
name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test-ubuntu-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          bash ./pytest.sh

  test-ubuntu-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Test with pytest
        env:
          CUDA_VISIBLE_DEVICES: -1
        run: |
          bash ./pytest.sh

  test-macos:
    runs-on: macOS-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          bash ./pytest.sh
